%% energy conversion for cold ions at the flux rope
% writen by Liangjin Song on 20210319
%%
clear;
%% parameters
indir='E:\PIC\Cold-Ions\mie25\data';
outdir='E:\PIC\Cold-Ions\mie25\out\Line\FR';
nx=1200;
ny=800;
nz=1;
di=20;

tt=47;

qi=0.000337;
n0=1481.487305;
vA=0.025;
norm=n0*vA*vA;

x0=0;
dir=0;

Lx=nx/di;
Ly=ny/di;

xrange=[0,Lx];
yrange=[-Ly/2,Ly/2];
range=[35,50];

%% read data
cd(indir)
Nic=pic3d_read_data('Nh',tt,nx,ny,nz);
Vic=pic3d_read_data('Vh',tt,nx,ny,nz);
E=pic3d_read_data('E',tt,nx,ny,nz);
B=pic3d_read_data('B',tt,nx,ny,nz);
ss=pic3d_read_data('stream',tt,nx,ny,nz);

%% calculation
cd(outdir);
% current generated by cold ions
Jic.x=Nic.*Vic.x;
Jic.y=Nic.*Vic.y;
Jic.z=Nic.*Vic.z;
% energy conversion
JicE=Jic.x.*E.x+Jic.y.*E.y+Jic.z.*E.z;

%% the overview of energy conversion for cold ions
h1=figure;
pic3d_plot_2D_base_field(JicE,Lx,Ly,norm); hold on
pic3d_plot_2D_stream(ss,Lx,Ly,20); hold off
caxis([-0.4,0.4]);
title(['Jic\cdot E, \Omega_{ci}t =',num2str(tt)]);
xlim([24,32]);
ylim([-4,4]);
set(gca,'FontSize',14);
print(h1,'-dpng','-r300',['Jic_dot_E_overview_t',num2str(tt),'.png']);

%% electric field
h2=figure;
pic3d_plot_2D_base_field(E.x,Lx,Ly,vA); hold on
cr=caxis;
pic3d_plot_2D_stream(ss,Lx,Ly,20); hold off
caxis([-0.5,0.5]);
title(['Ex, \Omega_{ci}t =',num2str(tt)]);
xlim([24,32]);
ylim([-4,4]);
set(gca,'FontSize',14);
print(h2,'-dpng','-r300',['Ex_overview_t',num2str(tt),'.png']);

h3=figure;
pic3d_plot_2D_base_field(E.y,Lx,Ly,vA); hold on
cr=caxis;
pic3d_plot_2D_stream(ss,Lx,Ly,20); hold off
caxis([-0.25,0.4]);
title(['Ey, \Omega_{ci}t =',num2str(tt)]);
xlim([24,32]);
ylim([-4,4]);
set(gca,'FontSize',14);
print(h3,'-dpng','-r300',['Ey_overview_t',num2str(tt),'.png']);

h4=figure;
pic3d_plot_2D_base_field(E.z,Lx,Ly,vA); hold on
cr=caxis;
pic3d_plot_2D_stream(ss,Lx,Ly,20); hold off
caxis(cr);
title(['Ez, \Omega_{ci}t =',num2str(tt)]);
xlim([24,32]);
ylim([-4,4]);
set(gca,'FontSize',14);
print(h2,'-dpng','-r300',['Ez_overview_t',num2str(tt),'.png']);

%% cold ions current
h5=figure;
pic3d_plot_2D_base_field(Jic.x,Lx,Ly,n0*vA); hold on
pic3d_plot_2D_stream(ss,Lx,Ly,20); hold off
caxis([-1,1]);
title(['Jic_x, \Omega_{ci}t =',num2str(tt)]);
xlim([24,32]);
ylim([-4,4]);
set(gca,'FontSize',14);
print(h5,'-dpng','-r300',['Jicx_overview_t',num2str(tt),'.png']);

h6=figure;
pic3d_plot_2D_base_field(Jic.y,Lx,Ly,n0*vA); hold on
cr=caxis;
pic3d_plot_2D_stream(ss,Lx,Ly,20); hold off
caxis(cr);
title(['Jic_y, \Omega_{ci}t =',num2str(tt)]);
xlim([24,32]);
ylim([-4,4]);
set(gca,'FontSize',14);
print(h6,'-dpng','-r300',['Jicy_overview_t',num2str(tt),'.png']);

h7=figure;
pic3d_plot_2D_base_field(Jic.z,Lx,Ly,n0*vA); hold on
cr=caxis;
pic3d_plot_2D_stream(ss,Lx,Ly,20); hold off
caxis(cr);
title(['Jic_z, \Omega_{ci}t =',num2str(tt)]);
xlim([24,32]);
ylim([-4,4]);
set(gca,'FontSize',14);
print(h7,'-dpng','-r300',['Jicz_overview_t',num2str(tt),'.png']);

%% the line of energy conversion
JEx=Jic.x.*E.x;
JEy=Jic.y.*E.y;
JEz=Jic.z.*E.z;
[lbz,lx]=get_line_data(B.z,Lx,Ly,x0,1,dir);
[ljex,~]=get_line_data(JEx,Lx,Ly,x0,norm,dir);
[ljey,~]=get_line_data(JEy,Lx,Ly,x0,norm,dir);
[ljez,~]=get_line_data(JEz,Lx,Ly,x0,norm,dir);
[ljice,~]=get_line_data(JicE,Lx,Ly,x0,norm,dir);
h8=figure;
plot(lx,ljex,'-r','LineWidth',1.5); hold on
plot(lx,ljey,'-g','LineWidth',1.5);
plot(lx,ljez,'-b','LineWidth',1.5);
plot(lx,ljice,'-k','LineWidth',1.5); hold off
title(['\Omega_{ci}t =',num2str(tt)]);
xlabel('X [c/\omega_{pi}]');
ylabel('Jic\cdot E');
legend('Jic_xE_x','Jic_yE_y','Jic_zE_z','Sum');
set(gca,'FontSize',14);
xlim([24,32]);
print(h8,'-dpng','-r300',['Jic_dot_E_line_t',num2str(tt),'.png']);

%% the line of electric field
[lex,~]=get_line_data(E.x,Lx,Ly,x0,vA,dir);
[ley,~]=get_line_data(E.y,Lx,Ly,x0,vA,dir);
[lez,~]=get_line_data(E.z,Lx,Ly,x0,vA,dir);
h9=figure;
plot(lx,lex,'-r','LineWidth',1.5); hold on
plot(lx,ley,'-g','LineWidth',1.5);
plot(lx,lez,'-b','LineWidth',1.5); hold off
title(['\Omega_{ci}t =',num2str(tt)]);
xlabel('X [c/\omega_{pi}]');
ylabel('Electric Field');
legend('E_x','E_y','E_z');
set(gca,'FontSize',14);
xlim([24,32]);
print(h9,'-dpng','-r300',['E_line_t',num2str(tt),'.png']);

%% the line of electric field
[ljicx,~]=get_line_data(Jic.x,Lx,Ly,x0,n0*vA,dir);
[ljicy,~]=get_line_data(Jic.y,Lx,Ly,x0,n0*vA,dir);
[ljicz,~]=get_line_data(Jic.z,Lx,Ly,x0,n0*vA,dir);
h10=figure;
plot(lx,ljicx,'-r','LineWidth',1.5); hold on
plot(lx,ljicy,'-g','LineWidth',1.5);
plot(lx,ljicz,'-b','LineWidth',1.5); hold off
title(['\Omega_{ci}t =',num2str(tt)]);
xlabel('X [c/\omega_{pi}]');
ylabel('Jic');
legend('Jic_x','Jic_y','Jic_z');
set(gca,'FontSize',14);
xlim([24,32]);
print(h10,'-dpng','-r300',['Jic_line_t',num2str(tt),'.png']);