%%
pic3d.asym_cold_slj.plot_pressure_work_as_time_whole_space;

pic3d.asym_cold_slj.plot_pressure_work_integral_as_time_whole_space;

pic3d.asym_cold_slj.plot_pressure_work_components_as_time_whole_space;

pic3d.asym_cold_slj.plot_pressure_work_components_integral_as_time_whole_space;

pic3d.asym_cold_slj.plot_total_energy_conversion_as_time_whole_space;

pic3d.asym_cold_slj.plot_energy_conversion_as_time;

pic3d.asym_cold_slj.plot_energy_conversion_integral_as_time_whole_space;

pic3d.asym_cold_slj.plot_thermal_energy_conversion_as_time_whole_space;